project:
  type: website

website:
  title: "Jie Hua's Bioinformatics Notes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jiehua1995

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

