project:
  type: website

website:
  title: "Jie Hua's Bioinformatics Notes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jiehua1995
  twitter-card: true
  open-graph: true

execute:
  freeze: auto

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

editor: visual

