project:
  type: website

website:
  title: "Jie Hua's Bioinformatics Notes"
  site-url: https://bioinfor.jiehua1995.xyz/
  reader-mode: true
  sidebar: false
  navbar:
    right:
      - about.qmd
      - 404.qmd
      - icon: github
        href: https://github.com/jiehua1995
      - icon: rss
        href: index.xml
  twitter-card: true
  open-graph: true
  bread-crumbs: true
  page-footer:
    border: false
    left: "Copyright © 2025, Jie Hua"
    right:
      - icon: globe
        href: https://jiehua1995.xyz
execute:
  freeze: auto

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

editor: visual

